version: 0.2

env:
  variables:
    NODE_ENV: "development"

phases:
  install:
  runtime-versions:
      nodejs: 12  
    commands:
      - echo Installing Node...
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building...
      - npm run build
      - npm start

cache:
  paths:
    - './node_modules/**/*'

artifacts:
  files:
    - index.js
    - build/**/*
    - node_modules/**/*